//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSignupLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string LoaiSP { get; set; }
        public decimal GiaBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MoTa { get; set; }
        public string ImageUrl { get; set; }
    }
}
